apiVersion: v1
kind: Service
metadata:
  name: patient-record-service
spec:
  selector:
    app: patient-record-service-green   # Initially points to Green
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer


# use app selector to route traffic
# spec:
#   selector:
#     app: patient-record-service-blue
