apiVersion: batch/v1
kind: CronJob
metadata:
  name: patient-aggregator-job
spec:
  schedule: "45 14 * * 0" # Adjust the schedule to run weekly at 14:45 UTC (9:45 AM ET on Sundays)
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: patient-aggregator-task-aggregate
            image: curlimages/curl:latest
            command: ["curl"]
            args: ["-X", "POST", "http://patient-aggregator-service.default.svc.cluster.local:5000/aggregate"]
          # - name: patient-aggregator-task-test
          #   image: curlimages/curl:latest
          #   command: ["curl"]
          #   args: ["-X", "GET", "http://patient-aggregator-service.default.svc.cluster.local:5000/test"]
          restartPolicy: OnFailure
