apiVersion: batch/v1
kind: CronJob
metadata:
  name: patient-aggregator-job
spec:
  schedule: "45 14 * * *" # Adjust the schedule to run daily at 9:30 AM UTC
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: patient-aggregator-task-appointments-per-doctor
            image: curlimages/curl:latest
            command: ["curl"]
            args: ["-X", "GET", "http://patient-aggregator-service.default.svc.cluster.local:5000/aggregator/appointments-per-doctor"]
          - name: patient-aggregator-task-appointment-frequency
            image: curlimages/curl:latest
            command: ["curl"]
            args: ["-X", "GET", "http://patient-aggregator-service.default.svc.cluster.local:5000/aggregator/appointment-frequency"]
          - name: patient-aggregator-task-common-conditions
            image: curlimages/curl:latest
            command: ["curl"]
            args: ["-X", "GET", "http://patient-aggregator-service.default.svc.cluster.local:5000/aggregator/common-conditions"]
          restartPolicy: OnFailure
