apiVersion: apps/v1
kind: Deployment
metadata:
  name: patient-aggregator-service
spec:
  replicas: 1  # Single replica since it's only used by the CronJob
  selector:
    matchLabels:
      app: patient-aggregator-service
  template:
    metadata:
      labels:
        app: patient-aggregator-service
    spec:
      containers:
      - name: patient-aggregator-service
        image: 182399719344.dkr.ecr.us-east-1.amazonaws.com/cc-patient-aggregator-service:latest  # Use your ECR image
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        env:
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: password
