apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
type: Opaque
data:
  username: YWRtaW4=   # base64 encoded value of 'username'
  password: cHctaGVhbHRoc3luYzMyMQ==   # base64 encoded value of 'password'
