apiVersion: apps/v1
kind: Deployment
metadata:
  name: patient-update-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: patient-update-service
  template:
    metadata:
      labels:
        app: patient-update-service
    spec:
      containers:
      - name: patient-update-service
        image: 182399719344.dkr.ecr.us-east-1.amazonaws.com/cc-patient-update-service:latest
        imagePullPolicy:  Always
        ports:
        - containerPort: 5000
        env:
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: password
